import type { DMO } from "./types";

export const MOCK_DMOS: DMO[] = [
  {
    id: "dmo_001",
    image_url: "https://picsum.photos/seed/muse1/800/600",
    image_placeholder: "linear-gradient(135deg, #F5D0CB 0%, #E8B5AE 50%, #D4958A 100%)",
    ui_type: "onboarding",
    design_style: ["whimsical", "playful"],
    color_palette: ["#F5D0CB", "#D4958A", "#2C1810", "#F8F4ED", "#C4955A"],
    typography: ["Playfair Display", "Space Grotesk"],
    layout: { grid: "column", density: "low" },
    components: ["button", "illustration", "progress-dots", "heading"],
    semantic_tags: ["high delight", "premium onboarding", "story-driven"],
    intent: { primary: "inspiration", confidence: 0.94 },
    source: { app: "Dribbble", url: null },
    project: "Onboarding Redesign",
    created_at: "2026-05-22T10:30:00Z",
  },
  {
    id: "dmo_002",
    image_url: "https://picsum.photos/seed/muse2/800/600",
    image_placeholder: "linear-gradient(135deg, #C4D9E5 0%, #8AAEC2 50%, #5C8BA8 100%)",
    ui_type: "dashboard",
    design_style: ["minimal", "corporate"],
    color_palette: ["#C4D9E5", "#8AAEC2", "#1E1409", "#F8F4ED", "#D9CCBA"],
    typography: ["Inter", "DM Mono"],
    layout: { grid: "bento", density: "high" },
    components: ["chart", "card", "navbar", "data-table", "badge"],
    semantic_tags: ["data-dense", "fintech", "professional clarity"],
    intent: { primary: "reference", confidence: 0.88 },
    source: { app: "Linear", url: null },
    project: "Analytics Dashboard",
    created_at: "2026-05-21T14:00:00Z",
  },
  {
    id: "dmo_003",
    image_url: "https://picsum.photos/seed/muse3/800/600",
    image_placeholder: "linear-gradient(135deg, #D0C8DF 0%, #A898C0 50%, #7B6A9C 100%)",
    ui_type: "pricing",
    design_style: ["luxury", "editorial"],
    color_palette: ["#D0C8DF", "#A898C0", "#7B6A9C", "#C4955A", "#F8F4ED"],
    typography: ["Cormorant Garamond", "Neue Haas Grotesk"],
    layout: { grid: "card", density: "low" },
    components: ["pricing-card", "toggle", "cta-button", "feature-list"],
    semantic_tags: ["conversion focused", "trust signals", "premium SaaS"],
    intent: { primary: "research", confidence: 0.91 },
    source: { app: "Loom", url: null },
    project: "Pricing Page",
    created_at: "2026-05-20T09:15:00Z",
  },
  {
    id: "dmo_004",
    image_url: "https://picsum.photos/seed/muse4/800/600",
    image_placeholder: "linear-gradient(135deg, #C3D4BF 0%, #8FA888 50%, #6A8866 100%)",
    ui_type: "modal",
    design_style: ["organic", "whimsical"],
    color_palette: ["#C3D4BF", "#8FA888", "#6A8866", "#F8F4ED", "#D4958A"],
    typography: ["Recoleta", "Inter"],
    layout: { grid: "freeform", density: "low" },
    components: ["modal", "avatar", "button", "input", "close-icon"],
    semantic_tags: ["soft UI", "friendly", "community-driven"],
    intent: { primary: "inspiration", confidence: 0.79 },
    source: { app: "Notion", url: null },
    project: "Component Library",
    created_at: "2026-05-19T16:45:00Z",
  },
  {
    id: "dmo_005",
    image_url: "https://picsum.photos/seed/muse5/800/600",
    image_placeholder: "linear-gradient(135deg, #1E1409 0%, #3D2B1A 50%, #C4955A 100%)",
    ui_type: "landing",
    design_style: ["brutalist", "editorial"],
    color_palette: ["#1E1409", "#3D2B1A", "#C4955A", "#F8F4ED", "#D9CCBA"],
    typography: ["Archivo Black", "Courier New"],
    layout: { grid: "hero", density: "medium" },
    components: ["hero", "navbar", "marquee", "grid-image", "cta-button"],
    semantic_tags: ["bold contrast", "editorial tension", "startup energy"],
    intent: { primary: "inspiration", confidence: 0.96 },
    source: { app: "Awwwards", url: null },
    project: "Brand Refresh",
    created_at: "2026-05-18T11:00:00Z",
  },
  {
    id: "dmo_006",
    image_url: "https://picsum.photos/seed/muse6/800/600",
    image_placeholder: "linear-gradient(135deg, #E2C89A 0%, #C4955A 50%, #9E7440 100%)",
    ui_type: "profile",
    design_style: ["luxury", "minimal"],
    color_palette: ["#E2C89A", "#C4955A", "#9E7440", "#1E1409", "#F8F4ED"],
    typography: ["PP Editorial New", "Helvetica Neue"],
    layout: { grid: "column", density: "low" },
    components: ["avatar", "stat-card", "tab", "portfolio-grid"],
    semantic_tags: ["premium creator", "portfolio", "high-trust"],
    intent: { primary: "reference", confidence: 0.85 },
    source: { app: "Read.cv", url: null },
    project: "Portfolio",
    created_at: "2026-05-17T08:30:00Z",
  },
  {
    id: "dmo_007",
    image_url: "https://picsum.photos/seed/muse7/800/600",
    image_placeholder: "linear-gradient(135deg, #EDCDC7 0%, #D4958A 50%, #CC7B6E 100%)",
    ui_type: "form",
    design_style: ["playful", "whimsical"],
    color_palette: ["#EDCDC7", "#D4958A", "#CC7B6E", "#C3D4BF", "#F8F4ED"],
    typography: ["Nunito", "Space Grotesk"],
    layout: { grid: "column", density: "medium" },
    components: ["input", "label", "checkbox", "radio", "button", "progress"],
    semantic_tags: ["delightful form", "low friction", "personality-driven"],
    intent: { primary: "inspiration", confidence: 0.82 },
    source: { app: "Typeform", url: null },
    project: "Onboarding Redesign",
    created_at: "2026-05-16T13:20:00Z",
  },
  {
    id: "dmo_008",
    image_url: "https://picsum.photos/seed/muse8/800/600",
    image_placeholder: "linear-gradient(135deg, #6BA3A3 0%, #4A8585 50%, #2D6666 100%)",
    ui_type: "navigation",
    design_style: ["minimal", "corporate"],
    color_palette: ["#6BA3A3", "#4A8585", "#2D6666", "#F8F4ED", "#1E1409"],
    typography: ["Satoshi", "JetBrains Mono"],
    layout: { grid: "freeform", density: "low" },
    components: ["sidebar", "nav-item", "icon", "badge", "search-bar"],
    semantic_tags: ["utility-first", "developer tool", "productivity"],
    intent: { primary: "reference", confidence: 0.77 },
    source: { app: "Figma", url: null },
    project: "Design System",
    created_at: "2026-05-15T10:00:00Z",
  },
  {
    id: "dmo_009",
    image_url: "https://picsum.photos/seed/muse9/800/600",
    image_placeholder: "linear-gradient(135deg, #F8F4ED 0%, #EEE8DA 40%, #D9CCBA 100%)",
    ui_type: "card",
    design_style: ["organic", "minimal"],
    color_palette: ["#F8F4ED", "#D9CCBA", "#8FA888", "#D4958A", "#C4955A"],
    typography: ["Fraunces", "Instrument Sans"],
    layout: { grid: "card", density: "medium" },
    components: ["card", "image", "tag", "button", "avatar"],
    semantic_tags: ["warm editorial", "content-first", "magazine feel"],
    intent: { primary: "inspiration", confidence: 0.90 },
    source: { app: "Are.na", url: null },
    project: "Content Platform",
    created_at: "2026-05-14T09:00:00Z",
  },
  {
    id: "dmo_010",
    image_url: "https://picsum.photos/seed/muse10/800/600",
    image_placeholder: "linear-gradient(135deg, #D0C8DF 0%, #B4A8C8 40%, #7B6A9C 100%)",
    ui_type: "onboarding",
    design_style: ["luxury", "whimsical"],
    color_palette: ["#D0C8DF", "#A898C0", "#7B6A9C", "#C4955A", "#1E1409"],
    typography: ["Canela", "GT Walsheim"],
    layout: { grid: "hero", density: "low" },
    components: ["hero", "step-indicator", "illustration", "cta-button"],
    semantic_tags: ["aspirational", "lifestyle brand", "high delight"],
    intent: { primary: "inspiration", confidence: 0.93 },
    source: { app: "Mobbin", url: null },
    project: "Onboarding Redesign",
    compressed: true,
    created_at: "2026-05-13T15:30:00Z",
  },
  {
    id: "dmo_011",
    image_url: "https://picsum.photos/seed/muse11/800/600",
    image_placeholder: "linear-gradient(135deg, #C4D9E5 0%, #8AAEC2 40%, #2C6E8A 100%)",
    ui_type: "dashboard",
    design_style: ["editorial", "minimal"],
    color_palette: ["#C4D9E5", "#8AAEC2", "#2C6E8A", "#F8F4ED", "#C4955A"],
    typography: ["Söhne", "Söhne Mono"],
    layout: { grid: "bento", density: "medium" },
    components: ["stat-card", "line-chart", "table", "filter", "date-picker"],
    semantic_tags: ["clean data viz", "SaaS metrics", "investor-ready"],
    intent: { primary: "research", confidence: 0.86 },
    source: { app: "Pitch", url: null },
    project: "Analytics Dashboard",
    compressed: true,
    created_at: "2026-05-12T11:45:00Z",
  },
  {
    id: "dmo_012",
    image_url: "https://picsum.photos/seed/muse12/800/600",
    image_placeholder: "linear-gradient(135deg, #EDCDC7 0%, #CC7B6E 40%, #A8574A 100%)",
    ui_type: "landing",
    design_style: ["playful", "organic"],
    color_palette: ["#EDCDC7", "#D4958A", "#CC7B6E", "#C3D4BF", "#F8F4ED"],
    typography: ["Roca", "Inter"],
    layout: { grid: "freeform", density: "medium" },
    components: ["hero", "feature-grid", "testimonial", "cta-section"],
    semantic_tags: ["consumer app", "Gen Z aesthetic", "conversion funnel"],
    intent: { primary: "inspiration", confidence: 0.88 },
    source: { app: "Layers.to", url: null },
    project: "Brand Refresh",
    created_at: "2026-05-11T08:00:00Z",
  },
];

export const PROJECTS = [
  "Onboarding Redesign",
  "Analytics Dashboard",
  "Pricing Page",
  "Component Library",
  "Brand Refresh",
  "Portfolio",
  "Design System",
  "Content Platform",
];

export const getDMO = (id: string) => MOCK_DMOS.find((d) => d.id === id);

export const getRelatedDMOs = (dmo: DMO, count = 3) =>
  MOCK_DMOS.filter(
    (d) =>
      d.id !== dmo.id &&
      (d.project === dmo.project ||
        d.design_style.some((s) => dmo.design_style.includes(s)))
  ).slice(0, count);
